/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.dialogs;

import controller.ProductoControlador;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.Alitas;
import model.Bebida;
import model.Papas;
import model.Pizza;
import model.Producto;
import model.listas.Dato;
import views.panels.BebidasAtributos;
import views.panels.PizzaAtributos;

/**
 *
 * @author luis
 */
public class ProductosDialog extends javax.swing.JDialog {

    /**
     * Variables para mover la ventana
     */
    int xMouse;
    int yMouse;

    JPanel panelActivo; 
    
    /**
     * Creates new form AltaProductosDialog
     */
    public ProductosDialog(java.awt.Frame parent, boolean modal, String title) {
        super(parent, modal);
        initComponents();
        txtTituloVentana.setText(title);
        changePanel(new PizzaAtributos());
    }

    /**
     * Funcion para cambiar el panel automatico 
     * de los productos 
     * @param panel es el tipo de panel que quiero mostrar
     */
    private void changePanel(JPanel panel) {
        jpEspecificos.removeAll();
        jpEspecificos.repaint();
        jpEspecificos.revalidate();
        panelActivo = panel;//sirve para recordar
        if (panel != null) {
            jpEspecificos.add(panel);
            jpEspecificos.repaint();
            jpEspecificos.revalidate();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTituloVentana = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbProducto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JFormattedTextField();
        jpEspecificos = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(86, 153, 65));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelTituloMouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelTituloPressed(evt);
            }
        });

        txtTituloVentana.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/res/icons8-cerrar-ventana-filled-15.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarVentanaClick(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTituloVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTituloVentana)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jLabel1.setText("Producto: ");

        cmbProducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PIZZA", "BEBIDA", "ALITAS", "PAPAS" }));
        cmbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductoAction(evt);
            }
        });

        jLabel3.setText("Clave: ");

        txtId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel4.setText("Precio:");

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel5.setText("Nombre producto:");

        txtPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtPrecio.setText("0.00");
        txtPrecio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jpEspecificos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Especificos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jpEspecificos.setMaximumSize(new java.awt.Dimension(334, 123));
        jpEspecificos.setMinimumSize(new java.awt.Dimension(334, 123));
        jpEspecificos.setName(""); // NOI18N
        jpEspecificos.setPreferredSize(new java.awt.Dimension(334, 123));
        jpEspecificos.setLayout(new java.awt.BorderLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/res/icons8-marca-de-verificacion-filled-32.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarClick(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpEspecificos, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpEspecificos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarVentanaClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarVentanaClick
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cerrarVentanaClick

    private void panelTituloPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTituloPressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelTituloPressed

    private void panelTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTituloMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelTituloMouseDragged

    private void cmbProductoAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductoAction

        System.out.println(cmbProducto.getSelectedItem().toString());
        switch (cmbProducto.getSelectedIndex()) {
            case 0:
                changePanel(new PizzaAtributos());
                break;
            case 1:
                changePanel(new BebidasAtributos());
                break;
            case 2:
            case 3:
                changePanel(null);
        }
    }//GEN-LAST:event_cmbProductoAction

    private void botonAceptarClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarClick
        
        ///Validacion 2

        if(txtId.getText().equals("") || 
                txtNombre.getText().equals(""))
        {
              JOptionPane.showMessageDialog(this, 
                     "Los campos no pueden estar vacíos","Error"
                    ,JOptionPane.ERROR_MESSAGE);             
            return; // Ya no sigas el metodo aqui ya se quebró
        }         
        ///Validacion 1
        String clave = txtId.getText();
        boolean existe = false; 
        for(Producto p : Dato.listaProductos)
            if(p.id.equals(clave)) // p.id == clave
                {existe = true; break;}
        if(existe)
        {
            JOptionPane.showMessageDialog(this, 
                     "El producto ya existe","Información"
                    ,JOptionPane.WARNING_MESSAGE);
            return; // Ya no sigas el metodo aqui ya se quebró
        }
        ///
        Producto producto;
        switch(cmbProducto.getSelectedIndex()){
            case 0: // pizza
                Pizza pizza = new Pizza();
                pizza.id = txtId.getText();
                pizza.nombre = txtNombre.getText(); 
                pizza.precio  = Double.parseDouble(txtPrecio.getText());
                // Regresar la funcionalidad de un hijo
                PizzaAtributos panelPizza = (PizzaAtributos)panelActivo;
                pizza.tam = panelPizza.cmbPizzaTam.getSelectedItem()
                                  .toString(); 
                pizza.borde = panelPizza.chkPizzaQueso.isSelected();                        
                producto = pizza; 
                break;
            case 1: // Bebidas
                Bebida bebida = new Bebida();
                bebida.id = txtId.getText(); 
                bebida.nombre = txtNombre.getText();
                bebida.precio = Double.parseDouble(txtPrecio.getText());
                BebidasAtributos ba = (BebidasAtributos)panelActivo; 
                bebida.tam = ba.txtTam.getText();
                if(convertidorsitoEnteros(bebida.tam,ba.txtTam)<=0)
                {
                      JOptionPane.showMessageDialog(this, 
                     "El tamaño no puede ser menor o cero","Error"
                    ,JOptionPane.ERROR_MESSAGE);             
                    return;
                }
                producto = bebida; 
                break; 
            case 2: 
                Alitas alita = new Alitas(); 
                alita.nombre = txtNombre.getText(); 
                alita.id = txtId.getText(); 
                alita.precio = Double.parseDouble(txtPrecio.getText());
                producto = alita;
                break;
            case 3: 
                Papas papas = new Papas(); 
                papas.nombre = txtNombre.getText(); 
                papas.id = txtId.getText(); 
                papas.precio = Double.parseDouble(txtPrecio.getText());
                producto = papas;
                break; 
            default:
                producto = null;
        }        
        // Controlador 
        ProductoControlador control = new ProductoControlador();
        control.agregarProducto(producto);
        System.out.println("Se registro");
        this.dispose();
        
    }//GEN-LAST:event_botonAceptarClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProductosDialog dialog = new ProductosDialog(new javax.swing.JFrame(), true, "Alta de productos");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpEspecificos;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtPrecio;
    private javax.swing.JLabel txtTituloVentana;
    // End of variables declaration//GEN-END:variables

    private int convertidorsitoEnteros(String tam,
                                                         JTextField txtTam) {
        int numero = 0; 
        try {
            numero = Integer.parseInt(tam); 
        } catch (Exception e) {
            numero = 0; 
        }
        txtTam.setText("" + numero);
        return numero;
    }
}
